server:
  tomcat:
    uri-encoding: UTF-8
  port: 8060

logging:
  level:
    org.springframework.web: ERROR
    net.consensys: DEBUG
    net.consensys.configs: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
  file: /logs/application.log

ethereum:
  nodes:
  - name: default
    url: ${ETHEREUM_NODE_URL:http://localhost:8545}
    blockStrategy: POLL
    syncingThreshold: 100
    healthcheckInterval: 3000
  healthcheck:
    pollInterval: 2000
  blockStrategy: POLL

#eventFilters:
#  - id: CryptoKittiesTransfer
#    contractAddress: "0x06012c8cf97bead5deae237070f9587f8e7a266d"
#    eventSpecification:
#      eventName: Transfer
#      nonIndexedParameterDefinitions:
#        - position: 0
#          type: ADDRESS
#        - position: 1
#          type: ADDRESS
#        - position: 2
#          type: UINT256
#
#    correlationId:
#      type: NON_INDEXED_PARAMETER
#      index: 2

#transactionFilters:
#- nodeName: ${ETHEREUM_NETWORK:DefaultNetwork}
#  type: "FROM_ADDRESS"
#  transactionIdentifierValue: ${CONTRACT_ADDRESS_EM_TOKEN:0x0f8E7A681019Ec13EfE853a6Eca666E05b214Fd5}
#  statuses: ['CONFIRMED']
#- nodeName: ${ETHEREUM_NETWORK:DefaultNetwork}
#  type: "TO_ADDRESS"
#  transactionIdentifierValue: ${CONTRACT_ADDRESS_EM_TOKEN:0xfBAB8dE62002c86986C6e070BD3bB46BF983C74e}
#  statuses: ['FAILED']

eventStore:
  type: DB
  url: http://localhost:8081/api/rest/v1
  eventPath: /event
  latestBlockPath: /latestblock
database:
  type: MONGO

broadcaster:
  type: KAFKA
  cache:
    expirationMillis: 6000000
  event:
    confirmation:
      numBlocksToWait: 12
      numBlocksToWaitForMissingTx: 100
      numBlocksToWaitBeforeInvalidating: 2
  multiInstance: false
  enableBlockNotifications: ${BROADCASTER_ENABLE_BLOCK_NOTIFICATION:true}

# For Kafka
zookeeper:
  address: ${ZOOKEEPER_ADDRESS:localhost:2181}
kafka:
  bootstrap:
    addresses: ${KAFKA_ADDRESSES:localhost:9092}
  topic:
    contractEvents: contract-events
    blockEvents: block-events
    eventeumEvents: eventeum-events
    transactionEvents: transaction-events

    partitions: 1
    replicationSets: 1

spring:
  rabbitmq:
    host: ${RABBIT_ADDRESS:localhost}

rabbitmq:
  exchange: ${RABBIT_EXCHANGE:ThisIsAExchange}
  routingKeyPrefix: ${RABBIT_ROUTING:thisIsRoutingKey}

management:
  endpoints:
    web.base-path: /monitoring
    enabled-by-default: false
    web.exposure.include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: false
    prometheus:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: false

